// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManager.Infrastructure;

#nullable disable

namespace OrderManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230317004530_LastMigration")]
    partial class LastMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManager.Domain.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OrderPrice")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalInfo = "Deliver only in extra hard packaging",
                            Address = "Bliżniąt 12/a",
                            City = "Poznań",
                            ClientName = "Viacheslav",
                            CreateDate = new DateTime(2023, 1, 23, 10, 14, 57, 26, DateTimeKind.Unspecified),
                            OrderPrice = 1049.96m,
                            Status = "Delivery"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalInfo = "shipping cost is calculated separately",
                            Address = "Szamarzewskiego 23",
                            City = "Wroclaw",
                            ClientName = "LuckyOnEnd",
                            CreateDate = new DateTime(2023, 2, 4, 8, 46, 34, 18, DateTimeKind.Unspecified),
                            OrderPrice = 499.99m,
                            Status = "Delivery"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalInfo = " ",
                            Address = "Bliżniąt 12/a",
                            City = "Poznań",
                            ClientName = "KaterinaMaslova",
                            CreateDate = new DateTime(2023, 1, 23, 10, 14, 57, 26, DateTimeKind.Unspecified),
                            OrderPrice = 600.00m,
                            Status = "Delivery"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalInfo = " ",
                            Address = "Slowackiego 37",
                            City = "Poznań",
                            ClientName = "EhorDev",
                            CreateDate = new DateTime(2023, 1, 23, 10, 14, 57, 26, DateTimeKind.Unspecified),
                            OrderPrice = 299.00m,
                            Status = "Delivery"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalInfo = " ",
                            Address = "",
                            City = "Gdańsk",
                            ClientName = "Sławek274",
                            CreateDate = new DateTime(2023, 1, 23, 10, 14, 57, 26, DateTimeKind.Unspecified),
                            OrderPrice = 356.00m,
                            Status = "Delivery"
                        });
                });

            modelBuilder.Entity("OrderManager.Domain.Entity.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderID = 1,
                            Price = 262.49m,
                            Product = "Battery"
                        },
                        new
                        {
                            Id = 2,
                            OrderID = 1,
                            Price = 262.49m,
                            Product = "Battery"
                        },
                        new
                        {
                            Id = 3,
                            OrderID = 1,
                            Price = 262.49m,
                            Product = "Battery"
                        },
                        new
                        {
                            Id = 4,
                            OrderID = 1,
                            Price = 262.49m,
                            Product = "Battery"
                        },
                        new
                        {
                            Id = 5,
                            OrderID = 2,
                            Price = 499.99m,
                            Product = "Smart Watch"
                        },
                        new
                        {
                            Id = 6,
                            OrderID = 3,
                            Price = 300.00m,
                            Product = "Wazon dla kwitów"
                        },
                        new
                        {
                            Id = 7,
                            OrderID = 3,
                            Price = 300.99m,
                            Product = "Wazon dla kwitów"
                        },
                        new
                        {
                            Id = 8,
                            OrderID = 4,
                            Price = 299.99m,
                            Product = "Zara - Kurtka Pikowana"
                        },
                        new
                        {
                            Id = 9,
                            OrderID = 5,
                            Price = 299.99m,
                            Product = "Mysz LOGITECH G502 Hero"
                        },
                        new
                        {
                            Id = 10,
                            OrderID = 5,
                            Price = 299.99m,
                            Product = "Mysz LOGITECH G102"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
